name: publish

on:
  push:
    branches:
      - develop
      - master

env:
  GRADLEW_ARGUMENTS: "--console=plain --stacktrace -Pci"

jobs:
  build_and_publish:
    runs-on: macos-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/gradle-wrapper-validation
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Add publishing secrets
        env:
          SIGNING_KEY_CONTENT_BASE64: ${{ secrets.SIGNING_KEY_CONTENT_BASE64 }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          CENTRAL_S01_USERNAME: ${{ secrets.CENTRAL_S01_USERNAME }}
          CENTRAL_S01_PASSWORD: ${{ secrets.CENTRAL_S01_PASSWORD }}
        run: |
          cd
          echo "$SIGNING_KEY_CONTENT_BASE64" | base64 --decode > key.gpg
          echo "signing.keyId=$SIGNING_KEY_ID" >> .gradle/gradle.properties
          echo "signing.password=$SIGNING_KEY_PASSWORD" >> .gradle/gradle.properties
          echo "signing.secretKeyRingFile=$(pwd)/key.gpg" >> .gradle/gradle.properties
          echo "publishing.central.s01.username=$CENTRAL_S01_USERNAME" >> .gradle/gradle.properties
          echo "publishing.central.s01.password=$CENTRAL_S01_PASSWORD" >> .gradle/gradle.properties

      - name: Publish to Central s01 snapshots
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: ./gradlew dabirva:publishMavenPublicationToCentralS01SnapshotsRepository $GRADLEW_ARGUMENTS

      - name: Publish to Central s01 staging
        if: ${{ github.ref == 'refs/heads/master' }}
        run: ./gradlew dabirva:publishMavenPublicationToCentralS01StagingRepository $GRADLEW_ARGUMENTS
